services:
  - type: web
    name: gtd-mini-bot
    env: python
    plan: free
    buildCommand: "cd bot && pip install -r requirements.txt"
    startCommand: "cd bot && uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
